name: Move card to assigned column

on:
  issues:
    assigned:
      types: [opened, reopened]

jobs:
  move-card:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get assigned user
        id: get_assignee
        run: |
          if [[ ${{ github.event.issue.assignee.login }} ]] 
          then
            assigned_user = "assignee=${{ github.event.issue.assignee.login }}"
          else
            assigned_user = "assignee=unassigned"
          fi
      - name: Get project information
        id: get_project
        run: |
          curl \
            -H "Authorization: Bearer ${{ secrets.FIRST }}" \
            https://api.github.com/repos/${{ github.repository }}/projects > /tmp/project_data.json
      - name: Move card to assigned column
        id: move_card
        run: |
          project_id=$(jq -r '.[0].id' < /tmp/project_data.json)
          assignee=assigned_user
          column_id=$(jq -r '.[0].columns[] | select(.name == "Assigned") | .id' < /tmp/project_data.json)
          card_id=$(jq -r '.[0].cards[] | select(.contentId == ${{ github.event.issue.number }}) | .id' < /tmp/project_data.json)
          rm /tmp/project_data.json
          if [[ $card_id != "" ]] 
          then
            curl \
              -X POST \
              -H "Authorization: Bearer ${{ secrets.FIRST }}" \
              https://api.github.com/projects/columns/$column_id/cards/$card_id/moves \
              -d "position=bottom"
          fi
