name: Move card to assigned column

on:
  issues:
    assigned:
      types: [opened, reopened]

jobs:
  move_card:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get issue and project data
        run: |
          issue_url="${{ github.event.issue.url }}"
          column_id=$(curl -sSfL "$issue_url/projects/columns?organization=YOUR_ORGANIZATION&repo=YOUR_REPOSITORY" | jq -r '.[] | select(.name == "Assigned") | .id')
          project_id=$(curl -sSfL "$issue_url/projects" | jq -r '.id')
        env:
          YOUR_ORGANIZATION: your_organization_name
          YOUR_REPOSITORY: your_repository_name
      - name: Get card ID for current issue
        run: |
          card_id=$(curl -sSfL "https://api.github.com/projects/columns/$column_id/cards?organization=$YOUR_ORGANIZATION&repo=$YOUR_REPOSITORY&per_page=100" | jq -r '.[] | select(.contentUrl == "{{ github.event.issue.url }}") | .id')
          if [[ -z "$card_id" ]]; then
            echo "Card for this issue not found in column: $column_id"
            exit 1
          fi
        env:
          YOUR_ORGANIZATION: your_organization_name
          YOUR_REPOSITORY: your_repository_name
      - name: Move card to Assigned column
        run: |
          curl -X POST https://api.github.com/projects/columns/$column_id/cards/$card_id/moves \
            -H "Authorization: ${{ secrets.GITHUB_TOKEN }}" \
            -d 'position=bottom'
        env:
          GITHUB_TOKEN: ${{ secrets.FIRST }}

