name: Move card to another column
on:
  issues:
    types: [assigned]
jobs:
  move-card:
    runs-on: ubuntu-latest
    steps:
      - name: Move card to another column
        uses: alex-page/github-project-automation-plus@7ffb872c64bd809d23563a130a0a97d01dfa8f43
        with:
          project: <PROJECT_NAME>
          column: <COLUMN_NAME>
          repo-token: ${{ secrets.FIRST }}
