name: Automating Assigned Section
on:
  issues:
    types:
      - assigned
jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: project
          column: Assigned
          repo-token: ${{ secrets.FIRST }}
